### ISSUE TITLE
Import Error while trying to import

### ISSUE THREAD

**Issue by thalishsajeed** [primetang/pylsd#6]
I installed the pylsd module using pip3 install pylsd

while trying to run import pylsd i get the below error

Unable to import the pylsd module
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thalish/.virtualenvs/lib/python3.5/site-packages/pylsd/__init__.py", line 8, in <module>
    from lsd import lsd
ImportError: cannot import name 'lsd'
```

Does the code not work for python 3.x ?

**Comment by getsanjeev** [comment]
same @primetang Any help?

**Comment by lan2720** [comment]
same problem

**Comment by n00blet** [comment]
pylsd has no support for python3 as far as I know
You can try this 
pip install ocrd-fork-pylsd >= 0.0.3

**Comment by ygest** [comment]
I run the code well with python
